# Generated by Django 5.2 on 2025-05-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_role_roleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(through='catalogue.ArtisteType', to='catalogue.type'),
        ),
        migrations.AlterUniqueTogether(
            name='artistetype',
            unique_together={('artist', 'type')},
        ),
        migrations.AddField(
            model_name='show',
            name='categories',
            field=models.ManyToManyField(blank=True, to='catalogue.category'),
        ),
        migrations.CreateModel(
            name='ShowArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
            options={
                'db_table': 'show_artist',
                'unique_together': {('show', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='show',
            name='artists',
            field=models.ManyToManyField(through='catalogue.ShowArtist', to='catalogue.artist'),
        ),
    ]
