# Generated by Django 5.2 on 2025-05-07 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Membre'), ('AFFILIATE', 'Affilié'), ('PRESS', 'Critique'), ('PRODUCER', 'Producteur'), ('ADMIN', 'Administrateur')], default='MEMBER', max_length=10)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('affiliation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
